FROM golang:1.8 as build-stage
WORKDIR /go/src/app
COPY hello-world.go .
RUN go build -o hello-world .


# starting second stage
FROM alpine:latest

# copy the binary from the `build-stage`
COPY --from=build-stage /go/src/app /bin

CMD hello-world